import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const docs: Array<[string, string]> = [
  ['privacy', 'docs/legal/uk-uk/privacy_policy.md'],
  ['terms', 'docs/legal/uk-uk/terms_of_use.md'],
  ['openSource', 'docs/legal/uk-uk/open_source.md'],
  ['about', 'docs/wordreapers_about.md'],
];

const entries = docs.map(([key, rel]) => {
  const text = readFileSync(join(root, rel), 'utf8');
  return `  ${key}: ${JSON.stringify(text)},`;
});

const outPath = join(root, 'lib/legal/bundled-legal.ts');
mkdirSync(dirname(outPath), { recursive: true });
const out = `/** Generated by scripts/bundle-legal-docs.ts — do not edit by hand. */\n\nexport const legalDocumentsUk = {\n${entries.join('\n')}\n} as const;\n\nexport type LegalDocumentKey = keyof typeof legalDocumentsUk;\n`;
writeFileSync(outPath, out);
console.log('Wrote', outPath);
